### ISSUE TITLE
Refactor to send back URL in POST request

### ISSUE THREAD

**Issue by jsjoeio** [Jbone187/urlshortner#1]
User should receive shortened URL in the response of the POST request.

Helpful link: https://stackoverflow.com/questions/19696240/proper-way-to-return-json-using-node-or-express

**Comment by Jbone187** [comment]
Url response was updated with code below

fetch("http://localhost:3000", {
    method: "POST",
    body: JSON.stringify({ url: data }),
    headers: {
      "Content-Type": "application/json"
    }
  })
    .then(function(response) {
      return response.json();
    })
    .then(function(data) {
      document.getElementById("json").innerHTML = JSON.stringify(data);
});
